# Go cross compiler (xgo): Wildcard layer to the latest Go release
# Copyright (c) 2014 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM karalabe/xgo-1.7.x

MAINTAINER Péter Szilágyi <peterke@gmail.com>
