# Go cross compiler (xgo): Go 1.12.x
# Copyright (c) 2020 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM karalabe/xgo-1.12.17

MAINTAINER Péter Szilágyi <peterke@gmail.com>
